name: stok_takibi
description: Stok takibi uygulaması - Flutter ile geliştirilmiş cross-platform mobil uygulama

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.4.3+1
  
  # HTTP Requests
  http: ^1.1.0
  dio: ^5.3.2
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  
  # UI Enhancements
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Barcode Scanner
  mobile_scanner: ^3.5.6
  
  # WebView
  webview_flutter: ^4.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true